Repository platform-coop-toolkit/coop-map-directory-index, pull requests merged in 2020-06, with the labels that each got.

#80 feat: add worker distribution (resolves #74)
  mdi/migrations/0073_add_worker_distribution.py
  mdi/models.py
Labels: enhancement

#82 chore(deps): update to Pinecone 1.0.0 beta.2
  maps/templates/lockdown/form.html
  maps/templates/maps/profiles/individual/basic_info.html
  maps/templates/maps/profiles/individual/contact_info.html
  maps/templates/maps/profiles/individual/detailed_info.html
  maps/templates/maps/profiles/individual/roles.html
  maps/templates/maps/profiles/individual/social_networks.html
  package-lock.json
  package.json
  surveys/templates/surveys/ecosystem_2020/basic_organization_info.html
  surveys/templates/surveys/ecosystem_2020/categories_challenges.html
  surveys/templates/surveys/ecosystem_2020/contact_info.html
  surveys/templates/surveys/ecosystem_2020/index.html
  surveys/templates/surveys/ecosystem_2020/social_networks.html
  templates/registration/password_reset_confirm.html
  templates/registration/password_reset_form.html
Labels: enhancement

#79 feat: add continuous deployment workflow
  .github/workflows/stack_demo.yml
  .github/workflows/stack_dev.yml
  Dockerfile
Labels: operations

#67 fix: restore Pinecone CSS to survey
  surveys/static/surveys/js/surveys.js
  surveys/templates/surveys/ecosystem_2020/base.html
Labels: bug

#91 feat: update Organization.code_availability to match data
  mdi/migrations/0075_update_code_availability.py
  mdi/models.py
Labels: enhancement

#93 feat: add Category.category_group
  mdi/admin.py
  mdi/migrations/0077_add_category_group.py
  mdi/models.py
Labels: enhancement

#95 feat: add Role.icon
  accounts/migrations/0045_add_role_icon.py
  accounts/models.py
Labels: enhancement

#97 feat: add my profiles flow (resolves #28)
  maps/forms.py
  maps/static/maps/css/app.scss
  maps/static/maps/images/archive.svg
  maps/static/maps/images/converting.svg
  maps/static/maps/images/coop-type.svg
  maps/static/maps/images/directory.svg
  maps/static/maps/images/document.svg
  maps/static/maps/images/language-small.svg
  maps/static/maps/images/notification.svg
  maps/static/maps/images/sector-small.svg
  maps/static/maps/js/app.js
  maps/static/maps/js/cards.js
  maps/templates/maps/header.html
  maps/templates/maps/my_profiles.html
  maps/templates/maps/partials/card_individual.html
  maps/templates/maps/partials/card_organization.html
  maps/templates/maps/partials/notification.html
  maps/urls.py
  maps/views.py
  webpack.mix.js
Labels: enhancement

#96 feat: replace category groups with types, surface type in admin (resolves #94)
  mdi/admin.py
  mdi/migrations/0078_category_group_to_type.py
  mdi/models.py
Labels: enhancement

#98 feat: replace Font Awesome with Pinecone icons
  accounts/migrations/0046_add_socialnetwork_icon.py
  accounts/models.py
  maps/static/maps/images/stack-exchange.svg
  maps/static/maps/js/app.js
  maps/templates/maps/individual_detail.html
  maps/templates/maps/organization_detail.html
  package-lock.json
  package.json
  templates/socialaccount/snippets/provider_list.html
Labels: dependencies, enhancement

#104 fix: remove django-autocomplete-light from cmdi/settings
  cmdi/settings.py
Labels: bug

#101 feat: add individual profile, clean up account/login/registration templates
  maps/static/maps/css/app.scss
  maps/static/maps/js/app.js
  maps/templates/maps/account_settings.html
  maps/templates/maps/base.html
  maps/templates/maps/header.html
  maps/templates/maps/individual_detail.html
  maps/templates/maps/my_profiles.html
  maps/templates/maps/partials/card_individual.html
  maps/templates/maps/partials/card_organization.html
  maps/templates/maps/profile.html
  maps/urls.py
  maps/views.py
  templates/account/account_inactive.html
  templates/account/base.html
  templates/account/email.html
  templates/account/email/email_confirmation_message.txt
  templates/account/email/email_confirmation_subject.txt
  templates/account/email/password_reset_key_message.txt
  templates/account/email_confirm.html
  templates/account/login.html
  templates/account/logout.html
  templates/account/messages/cannot_delete_primary_email.txt
  templates/account/messages/email_confirmation_sent.txt
  templates/account/messages/email_deleted.txt
  templates/account/messages/logged_in.txt
  templates/account/messages/logged_out.txt
  templates/account/messages/primary_email_set.txt
  templates/account/messages/unverified_primary_email.txt
  templates/account/password_change.html
  templates/account/password_reset.html
  templates/account/password_reset_done.html
  templates/account/password_reset_from_key.html
  templates/account/password_reset_from_key_done.html
  templates/account/password_set.html
  templates/account/signup.html
  templates/account/signup_closed.html
  templates/account/verification_sent.html
  templates/account/verified_email_required.html
  templates/django_registration/activation_complete.html
Labels: enhancement

#106 refactor: re: #102; creates & populates mdi_source
  accounts/admin.py
  accounts/migrations/0047_move_source_to_mdi_nd_drop.py
  accounts/models.py
  mdi/migrations/0079_move_source_to_mdi.py
  mdi/migrations/0080_truncate_and_fill_mdi_source.py
  mdi/migrations/0081_alter_organization_to_use_mdi_source.py
  mdi/models.py
Labels: data, enhancement

#107 feat: add Organization.code_url
  mdi/migrations/0082_add_code_url.py
  mdi/models.py
Labels: enhancement

#108 feat: add full profile view for organizations (resolves #6)
  maps/static/maps/css/app.scss
  maps/static/maps/js/app.js
  maps/templates/maps/individual_detail.html
  maps/templates/maps/my_profiles.html
  maps/templates/maps/organization_detail.html
  maps/templates/maps/partials/card_individual.html
  maps/templates/maps/partials/card_organization.html
  maps/templates/maps/partials/card_tool.html
  maps/views.py
  mdi/models.py
Labels: enhancement

#110 docs: update development documentation
  README.md
Labels: documentation

#111 feat: add Type.icon
  mdi/migrations/0083_add_type_icon.py
  mdi/models.py
Labels: enhancement

#112 feat: use Type.icon, create icon inclusion tag
  maps/static/maps/images/shared-platform.svg
  maps/templates/maps/about.html
  maps/templates/maps/account_settings.html
  maps/templates/maps/footer.html
  maps/templates/maps/global_nav.html
  maps/templates/maps/header.html
  maps/templates/maps/index.html
  maps/templates/maps/individual_detail.html
  maps/templates/maps/my_profiles.html
  maps/templates/maps/organization_detail.html
  maps/templates/maps/partials/card_individual.html
  maps/templates/maps/partials/card_organization.html
  maps/templates/maps/partials/card_tool.html
  maps/templates/maps/partials/icon.html
  maps/templates/maps/partials/notification.html
  maps/templates/maps/privacy_policy.html
  maps/templates/maps/profiles/back.html
  maps/templates/maps/profiles/back_and_steps.html
  maps/templates/maps/profiles/cancel.html
  maps/templates/maps/profiles/done.html
  maps/templates/maps/profiles/errors.html
  maps/templates/maps/profiles/footer.html
  maps/templates/maps/profiles/individual/basic_info.html
  maps/templates/maps/profiles/individual/contact_info.html
  maps/templates/maps/profiles/individual/detailed_info.html
  maps/templates/maps/profiles/individual/more_about_you.html
  maps/templates/maps/profiles/individual/roles.html
  maps/templates/maps/profiles/individual/social_networks.html
  maps/templates/maps/profiles/organization/basic_info.html
  maps/templates/maps/profiles/organization/contact_info.html
  maps/templates/maps/profiles/organization/detailed_info.html
  maps/templates/maps/profiles/organization/org_type.html
  maps/templates/maps/profiles/organization/scope_and_impact.html
  maps/templates/maps/profiles/organization/social_networks.html
  maps/templates/maps/search--home.html
  maps/templates/maps/search.html
  maps/templates/maps/terms_of_service.html
  maps/templatetags/maps_extras.py
Labels: enhancement

#113 Geocoding steps
  maps/forms.py
  maps/static/maps/css/app.scss
  maps/static/maps/js/app.js
  maps/templates/maps/index.html
  maps/templates/maps/profiles/individual/basic_info.html
  maps/templates/maps/profiles/individual/contact_info.html
  maps/templates/maps/profiles/individual/detailed_info.html
  maps/templates/maps/profiles/individual/geolocation.html
  maps/templates/maps/profiles/individual/more_about_you.html
  maps/templates/maps/profiles/individual/roles.html
  maps/templates/maps/profiles/individual/social_networks.html
  maps/templates/maps/profiles/organization/geolocation.html
  maps/views.py
Labels: enhancement

#105 fix: read email settings from environment variables
  cmdi/settings.py
Labels: enhancement

#116 ci: add pycodestyle linting (resolves #114)
  .github/workflows/lint.yml
  .pylintrc
  accounts/models.py
  cmdi/settings.py
  cmdi/urls.py
  maps/forms.py
  maps/views.py
  mdi/admin.py
  mdi/models.py
  mdi/tests.py
  mdi/urls.py
  mdi/views.py
  setup.cfg
  surveys/forms.py
  surveys/models.py
  surveys/views.py
Labels: enhancement

#121 feat: read debug option from environment variable
  cmdi/settings.py
  docker-compose.yml
Labels: enhancement

#124 feat: add link to Tool Library to global navigation
  maps/templates/maps/global_nav.html
Labels: enhancement

#123 fix: prevent appearance of duplicate messages (resolves #99)
  maps/templates/maps/account_settings.html
  maps/templates/maps/index.html
  maps/templates/maps/individual_detail.html
  maps/templates/maps/my_profiles.html
  maps/templates/maps/organization_detail.html
  maps/templates/maps/partials/messages.html
Labels: bug

#119 feat: add a tool flow (resolves #37)
  maps/forms.py
  maps/static/maps/css/app.scss
  maps/static/maps/js/app.js
  maps/templates/maps/profiles/tool/basic_info.html
  maps/templates/maps/profiles/tool/detailed_info.html
  maps/templatetags/maps_extras.py
  maps/urls.py
  maps/views.py
  mdi/admin.py
  mdi/migrations/0084_alter_tool_choices.py
  mdi/migrations/0085_add_tool_submitted_by_email.py
  mdi/models.py
  mdi/views.py
  setup.cfg
Labels: enhancement
