Repository platform-coop-toolkit/coop-map-directory-index, pull requests merged in 2020-05, with the labels that each got.

#34 fix: update contact email
  cmdi/urls.py
  maps/static/maps/components/detail/footer.html
  maps/static/maps/components/preview/archive--default.html
  maps/static/maps/components/preview/archive--unfiltered.html
  maps/static/maps/components/preview/archive.html
  maps/static/maps/components/preview/favorites.html
  maps/static/maps/components/preview/footer.html
  maps/static/maps/components/preview/home.html
  maps/static/maps/components/preview/page.html
  maps/static/maps/components/preview/resource.html
  maps/static/maps/components/preview/search-results--default.html
  maps/static/maps/components/preview/search-results--unfiltered.html
  maps/static/maps/components/preview/search-results.html
  maps/static/maps/components/preview/term-list--coop-types.html
  maps/static/maps/components/preview/term-list--default.html
  maps/static/maps/components/preview/term-list--formats.html
  maps/static/maps/components/preview/term-list--goals.html
  maps/static/maps/components/preview/term-list--sectors.html
  maps/static/maps/components/preview/term-list--topics.html
  maps/static/maps/components/preview/term-list.html
  maps/static/maps/components/render/footer.html
  maps/templates/maps/footer.html
  maps/templates/maps/privacy_policy.html
  surveys/templates/surveys/ecosystem_2020/index.html
Labels: enhancement

#58 chore(docs): add license
  LICENSE
  package.json
Labels: documentation

#60 feat: add about page (resolves #52)
  maps/static/maps/css/app.scss
  maps/templates/maps/about.html
  maps/templates/maps/base.html
  maps/templates/maps/header.html
  maps/templates/maps/index.html
  maps/templates/maps/individual_detail.html
  maps/templates/maps/organization_detail.html
  maps/templates/maps/privacy_policy.html
  maps/templates/maps/profile.html
  maps/templates/maps/search.html
  maps/templates/maps/terms_of_service.html
  maps/templatetags/maps_extras.py
  maps/urls.py
  maps/views.py
Labels: enhancement

#56 feat: add docker-compose
  docker-compose.yml
Labels: operations

#59 feat: add 'made by a cooperative' field to tools model
  mdi/migrations/0069_add_coop_made.py
  mdi/models.py
  mdi/serializers.py
Labels: enhancement

#63 ci: add GitHub Actions for testing
  .github/workflows/lint.yml
  .stylelintrc
  maps/static/maps/css/app.scss
  package-lock.json
  package.json
Labels: enhancement

#66 feat: add license type field (resolves #61)
  mdi/migrations/0070_add_tool_license_type.py
  mdi/models.py
Labels: enhancement
